# Generated by Django 2.0.9 on 2020-05-17 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_ocean', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExchangeDataFop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('start_number', models.CharField(max_length=20, null=True)),
                ('end_date', models.DateField(null=True)),
                ('end_number', models.CharField(max_length=20, null=True)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Authority')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('fullname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500, null=True)),
                ('registration_date', models.DateField(null=True)),
                ('registration_info', models.CharField(max_length=300, null=True)),
                ('estate_manager', models.CharField(max_length=100, null=True)),
                ('termination_date', models.DateField(null=True)),
                ('terminated_info', models.CharField(max_length=300, null=True)),
                ('termination_cancel_info', models.CharField(max_length=100, null=True)),
                ('contact_info', models.CharField(max_length=100, null=True)),
                ('vp_dates', models.CharField(max_length=100, null=True)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Authority')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FopToKved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('primary_kved', models.BooleanField(default=False)),
                ('fop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kveds', to='business_register.Fop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Founders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('founder', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.Division')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalFop',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('fullname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500, null=True)),
                ('registration_date', models.DateField(null=True)),
                ('registration_info', models.CharField(max_length=300, null=True)),
                ('estate_manager', models.CharField(max_length=100, null=True)),
                ('termination_date', models.DateField(null=True)),
                ('terminated_info', models.CharField(max_length=300, null=True)),
                ('termination_cancel_info', models.CharField(max_length=100, null=True)),
                ('contact_info', models.CharField(max_length=100, null=True)),
                ('vp_dates', models.CharField(max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('authority', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data_ocean.Authority')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data_ocean.Status')),
            ],
            options={
                'verbose_name': 'historical fop',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Kved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.Division')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rfop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('fullname', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('kved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.Kved')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ruo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=500, null=True)),
                ('short_name', models.CharField(max_length=500, null=True)),
                ('edrpou', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('boss', models.CharField(max_length=250, null=True)),
                ('kved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.Kved')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ruo',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.State'),
        ),
        migrations.AddField(
            model_name='rfop',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.State'),
        ),
        migrations.AddField(
            model_name='kved',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.Section'),
        ),
        migrations.AddField(
            model_name='group',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.Section'),
        ),
        migrations.AddField(
            model_name='founders',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founders', to='business_register.Ruo'),
        ),
        migrations.AddField(
            model_name='foptokved',
            name='kved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.Kved'),
        ),
        migrations.AddField(
            model_name='exchangedatafop',
            name='fop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_data', to='business_register.Fop'),
        ),
        migrations.AddField(
            model_name='exchangedatafop',
            name='taxpayer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ocean.TaxpayerType'),
        ),
        migrations.AddField(
            model_name='division',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.Section'),
        ),
    ]
